name: CI run on PR
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

env:
  # Golang version to use across CI steps
  GOLANG_VERSION: '1.26' 

permissions:
  contents: read

jobs:
  codechanges:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-22.04
    outputs:
      backend: ${{ steps.filter.outputs.backend_any_changed }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v4.0.0
      - uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        id: filter
        with:
          # Any file which is not under docs/ or is not a markdown file is counted as a backend file
          files_yaml: |
            backend:
              - go.mod
              - go.sum
              - '**.go'
              - '.github/workflows/ci-run-on-pr.yaml'

  check-go:
    name: Ensure Go modules synchronicity
    runs-on: ubuntu-22.04
    if: ${{ needs.codechanges.outputs.backend == 'true' && github.event.pull_request.draft == false}}
    needs:
      - codechanges
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v4.0.0
      - name: Setup Golang
        uses: actions/setup-go@c0137caad775660c0844396c52da96e560aba63d # v5.0.2
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - name: Download all Go modules
        run: |
          go mod download
      - name: Check for tidiness of go.mod and go.sum
        run: |
          go mod tidy
          git diff --exit-code -- .

  lint-go:
    name: Lint Go code
    runs-on: ubuntu-22.04
    if: ${{ needs.codechanges.outputs.backend == 'true' && github.event.pull_request.draft == false}}
    needs:
      - codechanges
    permissions:
      contents: read # for actions/checkout to fetch code
      pull-requests: read # for golangci/golangci-lint-action to fetch pull requests
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v4.0.0
      - name: Setup Golang
        uses: actions/setup-go@c0137caad775660c0844396c52da96e560aba63d # v5.0.2
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          args: --verbose

  unittests:
    name: Run unittests
    runs-on: ubuntu-22.04
    if: ${{ needs.codechanges.outputs.backend == 'true' && github.event.pull_request.draft == false}}
    needs:
      - codechanges
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.3
      - name: Setup Golang
        uses: actions/setup-go@c0137caad775660c0844396c52da96e560aba63d # v5.0.2
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - name: Integration tests
        run: |
          make check-coverage
